name: biomass
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy
  - open3d
  - matplotlib
  - opencv
  - pillow
  - pytorch=2.2.0
  - torchvision
  - cudatoolkit=11.8  # Aligning CUDA version with pytorch+cu118
  - shapely
  - alphashape=1.3.1
  - pyvista=0.38.5
  - trame
  - pip:
    - git+https://github.com/luca-medeiros/lang-segment-anything.git
